[tasks.ap-elf]
description = "Install aggchain proof ELF file"
run_task = "ap-elf-build"

[tasks.ap-elf-build]
description = "Compile aggchain proof ELF file"
env = { AGGLAYER_ELF_BUILD = "update" }
command = "cargo"
args = [
    "build",
    "-vv",
    "-paggchain-proof-builder",
]
