[env]
SP1_DOCKER_TAG="v4.1.3"

[tasks.ap-elf]
description = "Install aggchain proof ELF file"
run_task = { name = [
    "op-succinct-vkeys",
    "ap-elf-build",
] }

[tasks.ap-elf-build]
description = "Compile aggchain proof ELF file"
dependencies = ["op-succinct-vkeys"]
cwd = "crates/aggchain-proof-program"
command = "cargo"
args = [
    "prove",
    "build",
    "--docker",
    "--tag=${SP1_DOCKER_TAG}",
    "--workspace-directory=../../",
    "--output-directory=elf/",
    "--elf-name=riscv32im-succinct-zkvm-elf",
]

[tasks.op-succinct-vkeys]
description = "Re-generate op-succinct vkey embedded constants"
command = "cargo"
args = [
    "run",
    "--features=regenerate",
    "-pproposer-vkeys-raw",
    "--bin=regenerate",
]
