[env]
SP1_DOCKER_TAG = "v5.0.0@sha256:52d9e522d1dcbc4062edee950391173aed752793c33361fb2cad44272027a68c"

[tasks.ap-elf]
description = "Install aggchain proof ELF file"
run_task = "ap-elf-build"

[tasks.ap-elf-build]
description = "Compile aggchain proof ELF file"
cwd = "crates/aggchain-proof-program"
command = "cargo"
args = [
    "prove",
    "build",
    "--docker",
    "--tag=${SP1_DOCKER_TAG}",
    "--workspace-directory=../../",
    "--output-directory=elf/",
    "--elf-name=riscv32im-succinct-zkvm-elf",
]
