[env]
SP1_DOCKER_TAG="v4.1.3@sha256:b94d8953d824bd9f80d7176e2eed11fde1f7689fc880f5c1fdd2ed812ead92a8"

[tasks.ap-elf]
description = "Install aggchain proof ELF file"
run_task = "ap-elf-build"

[tasks.ap-elf-build]
description = "Compile aggchain proof ELF file"
cwd = "crates/aggchain-proof-program"
command = "cargo"
args = [
    "prove",
    "build",
    "--docker",
    "--tag=${SP1_DOCKER_TAG}",
    "--workspace-directory=../../",
    "--output-directory=elf/",
    "--elf-name=riscv32im-succinct-zkvm-elf",
]
