[package]
name = "agglayer-config"
version.workspace = true
edition.workspace = true

[dependencies]
ethers-gcp-kms-signer.workspace = true
ethers.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
thiserror.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
url = { workspace = true, features = ["serde"] }

agglayer-signer = { path = "../agglayer-signer" }

[features]
default = []
testutils = []
