[package]
name = "agglayer-prover-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
toml.workspace = true

prover-logger.workspace = true
prover-utils.workspace = true
prover-config.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["toml", "redactions", "filters"] }
pretty_assertions = "1.4.0"

