[package]
name = "aggchain-proof-multisig-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives.workspace = true
unified-bridge.workspace = true
agglayer-primitives.workspace = true
serde.workspace = true

[lints]
workspace = true
