use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

use aggchain_proof_builder::{
    AggchainProofBuilderService, AgghcainProofBuilderRequest as ProofBuilderRequest,
};
use aggkit_prover_config::aggchain_proof::AggchainProofServiceConfig;
use aggkit_prover_types::{AggchainProof, Hash};
use proposer_service::{ProposerService, Request as ProposerRequest};

use super::error::Error;

/// Request to the AggchainProofService to generate the
/// aggchain proof for the range of blocks.
#[derive(Default, Clone, Debug)]
pub struct ProofRequest {
    /// Aggchain proof starting block
    pub start_block: u64,
    /// Max number of blocks that the aggchain proof could contain
    pub max_block: u64,
    /// L1 Info tree root hash.
    pub l1_info_tree_root: Hash,
    /// L1 Info tree leaf hash.
    pub l1_info_tree_leaf: Hash,
    /// L1 Info tree proof.
    pub l1_info_tree_proof: [Hash; 32],
}

/// Resulting generated Aggchain proof
pub struct ProofResponse {
    proof: AggchainProof,
}

/// The Aggchain proof service is responsible for orchestrating an Aggchain
/// proof generation.
///
/// The Aggchain proof is generated by fetching the Aggregated FEP from the
/// proposer service and the aggchain proof builder service to generate the
/// Aggchain proof.
#[derive(Clone)]
pub(crate) struct AggchainProofService {
    pub(crate) proposer_service: ProposerService,
    pub(crate) aggchain_proof_builder: AggchainProofBuilderService,
}

impl AggchainProofService {
    pub fn new(_config: AggchainProofServiceConfig) -> Result<Self, Error> {
        todo!()
    }
}

impl tower::Service<ProofRequest> for AggchainProofService {
    type Response = ProofResponse;
    type Error = Error;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        if self
            .proposer_service
            .poll_ready(cx)
            .map_err(|_| Error::Noop)
            .is_pending()
        {
            return Poll::Pending;
        }

        self.aggchain_proof_builder
            .poll_ready(cx)
            .map_err(|_| Error::Noop)
    }

    fn call(&mut self, _req: ProofRequest) -> Self::Future {
        let mut proposer_client = self.proposer_service.clone();
        let mut proof_builder = self.aggchain_proof_builder.clone();

        let fut = async move {
            // Fetch Aggregated FEP
            let _result = proposer_client.call(ProposerRequest {}).await.unwrap();
            // Fetch the private inputs for Aggchain proof
            proof_builder.call(ProofBuilderRequest {}).await.unwrap();
            // Generate Aggchain proof

            Ok(ProofResponse {
                proof: AggchainProof::default(),
            })
        };

        Box::pin(fut)
    }
}
